version: '{build}'
os: Windows Server 2012 R2
environment:
  DOKAN_HOME: C:\Program Files (x86)\Dokan\DokanLibrary
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  VisualStudioVersion: 12.0
  CI_DEPLOY_USERNAME:
    secure: KcJMy3M1M+wPExeKn0lvLA==
  CI_DEPLOY_PASSWORD:
    secure: 09SvkofvJRaojG7QHCVy7GIdcLvxmJbJX/qimwfbSAvR4uzG7MohJEEkJj0CwRCQ

install:
- ps: $x64items = @(Get-ChildItem "HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall")
      $x64items + @(Get-ChildItem "HKLM:SOFTWARE\wow6432node\Microsoft\Windows\CurrentVersion\Uninstall") `
         | ForEach-object { Get-ItemProperty Microsoft.PowerShell.Core\Registry::$_ } `
         | Sort-Object -Property DisplayName `
         | Select-Object -Property DisplayName,DisplayVersion
   
- ps: Start-FileDownload 'https://github.com/Maxhy/dokany/releases/download/0.7.1/DokanInstall_0.7.1.exe'
- cmd: .\DokanInstall_0.7.1 /S

build_script:
- cmd: .\gradlew build

on_success:
- ps: >-
    if($env:appveyor_repo_branch -eq 'master') {
      cmd /c .\gradlew publish 2`>`&1
    }
