version: '{build}'
os: Windows Server 2012 R2
environment:
  DOKAN_HOME: C:\Program Files (x86)\Dokan\DokanLibrary
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  CI_DEPLOY_USERNAME:
    secure: KcJMy3M1M+wPExeKn0lvLA==
  CI_DEPLOY_PASSWORD:
    secure: 09SvkofvJRaojG7QHCVy7GIdcLvxmJbJX/qimwfbSAvR4uzG7MohJEEkJj0CwRCQ

install:
- ps: Start-FileDownload 'https://github.com/Maxhy/dokany/releases/download/0.7.1/DokanInstall_0.7.1.exe'
- cmd: .\DokanInstall_0.7.1 /S

build_script:
- cmd: .\gradlew build

on_success:
- ps: >-
    if($env:appveyor_repo_branch -eq 'deploy-only-from-master') {
      .\gradlew publish 2>&1
    }